name = "autodiscover-response"
type = 'javascript'
account_id = '8ea70b72cd30a9295d3a0a655ceb0b9a'
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "javascript"
kv_namespaces = [
         { binding = "AUTODISCOVER", id = "431bd71253c940be939e9cac18dac9fc", preview_id = "574c57433043400abf1eced3e3d0139b" }
]
